#========================================
# Test profile settings (IT tests)
#========================================
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///
  flyway:
    enabled: true
integration:
  samba:
    host: localhost
    port: 445
    domain: WORKGROUP
    username: user
    password: password
    share: /share/
    publ-folder: /publ/
