CREATE TABLE FILM
(
    FILM_ID        bigint NOT NULL PRIMARY KEY,
    FILNAMN        varchar(256),
    FILM_OBJ_FIL   varchar(256),
    OBJTYP         varchar(8),
    DATUM          varchar(256),
    DOKTITEL       varchar(2256),
    FILM_T_ID      bigint DEFAULT 1,
    FILM_OPLATS    varchar(64),
    FILM_O_ID      bigint DEFAULT 1,
    FILM_U_E_ID    bigint DEFAULT 0,
    FILM_U_J_ID    bigint DEFAULT 1,
    KOMMENT_FILM   varchar(4000),
    FILM_MIME_TYPE varchar(50),
    ASV            varchar(20),
    NODEID         bigint,
    `OPTIONS`      bigint DEFAULT 0,
    DELETEDDATE    date,
    FULLTEXT INDEX ft_film_doktitel_komment (DOKTITEL, KOMMENT_FILM)
) ENGINE = InnoDB;

CREATE TABLE PUBL
(
    P_ID          bigint NOT NULL PRIMARY KEY,
    FILNAMN       varchar(256),
    PUBLIKTYP     varchar(40),
    DATUM         varchar(10),
    TIDTITEL      varchar(128),
    TIDNR         varchar(5),
    TIDSIDA       varchar(3),
    BF_J_ID       bigint     DEFAULT 1,
    FORLAG_T_ID   bigint     DEFAULT 1,
    FORLAG_OPLATS varchar(64),
    DOKDATUM      varchar(10),
    DOKTITEL      varchar(256),
    F_E_ID        bigint     DEFAULT 0,
    R_E_ID        bigint     DEFAULT 0,
    U_J_ID        bigint     DEFAULT 1,
    U_E_ID        bigint     DEFAULT 0,
    P_T_ID        bigint     DEFAULT 1,
    P_OPLATS      varchar(64),
    ME_O_ID       bigint     DEFAULT 1,
    KOMMENT_PUBL  varchar(4000),
    FIL_LITEN     varchar(256),
    FIL_STOR      varchar(256),
    FIL_ORIGINAL  varchar(256),
    FIL_TXT       varchar(256),
    XMLTEXT       longtext,
    FIL_XTRA      varchar(256),
    NODEID        bigint,
    `OPTIONS`     bigint     DEFAULT 0,
    FIL_FORMAT    varchar(4) DEFAULT 'text',
    DELETEDDATE   date,
    FULLTEXT INDEX ft_publ_doktitel_komment_xmltext (DOKTITEL, KOMMENT_PUBL, XMLTEXT)
) ENGINE = InnoDB;

CREATE TABLE FOTO
(
    F_ID             bigint NOT NULL PRIMARY KEY,
    M_I_ID           bigint        DEFAULT 1,
    U_E_ID           bigint        DEFAULT 0,
    U_J_ID           bigint        DEFAULT 1,
    VERKPERIOD_START varchar(10),
    VERKPERIOD_SLUT  varchar(10),
    KOMMENT_UPPH     varchar(1000),
    VERKORT_T_ID     bigint,
    B_J_ID           bigint        DEFAULT 1,
    B_E_ID           bigint        DEFAULT 0,
    B_T_ID           bigint        DEFAULT 1,
    A_E_ID           bigint        DEFAULT 0,
    A_J_ID           bigint        DEFAULT 1,
    G_E_ID           bigint        DEFAULT 0,
    G_J_ID           bigint        DEFAULT 1,
    G_RATTIGH        varchar(1000),
    G_FORBEH         varchar(3),
    ANVANDO          varchar(1000),
    ACCNR            varchar(15),
    TIDIG            varchar(10),
    SENAST           varchar(10),
    DOKTITEL         varchar(256),
    F_T_ID           bigint        DEFAULT 1,
    SAKORD           varchar(128),
    KOMMENT_FF       varchar(4000),
    REFKOD           varchar(15),
    TIDIGNR          varchar(30),
    INVENTNR         varchar(15),
    FILNAMN          varchar(256),
    FIL_LITEN        varchar(256),
    FIL_STOR         varchar(256),
    FIL_ORIGINAL     varchar(256),
    HOJD             varchar(20),
    BREDD            varchar(20),
    SVVITFARG        varchar(10),
    NEGPOS           varchar(10),
    GENPAS           varchar(10),
    BILDBAR          varchar(10),
    DIAM             varchar(20),
    MATERIAL         varchar(50),
    FUNKTION         varchar(500),
    TEKNIK           varchar(50),
    RAM              varchar(10),
    TILLSKAT         varchar(60),
    TILLSTAND        varchar(1000),
    OBSDATUM         varchar(10),
    OBSNAMN          varchar(50),
    ATGARD           varchar(1000),
    ATDDATUM         varchar(10),
    SIGN             varchar(30),
    FORPLATS         varchar(35),
    OVRIGT           varchar(30),
    OBJTYP           varchar(10),
    F_OPLATS         varchar(64),
    NODEID           bigint,
    `OPTIONS`        bigint        DEFAULT 0,
    DELETEDDATE      date,
    FULLTEXT INDEX ft_foto_doktitel_komment (DOKTITEL, KOMMENT_FF)
) ENGINE = InnoDB;

CREATE TABLE TOPOGRAFI
(
    T_ID    bigint NOT NULL PRIMARY KEY,
    TOPNAMN varchar(64),
    TOPKOD  varchar(6),
    PLATS   varchar(64),
    LAND    varchar(64)
) ENGINE = InnoDB;
