CREATE TABLE FOTO
(
    F_ID             bigint NOT NULL PRIMARY KEY,
    M_I_ID           bigint        DEFAULT 1,
    U_E_ID           bigint        DEFAULT 0,
    U_J_ID           bigint        DEFAULT 1,
    VERKPERIOD_START varchar(10),
    VERKPERIOD_SLUT  varchar(10),
    KOMMENT_UPPH     varchar(1000),
    VERKORT_T_ID     bigint,
    B_J_ID           bigint        DEFAULT 1,
    B_E_ID           bigint        DEFAULT 0,
    B_T_ID           bigint        DEFAULT 1,
    A_E_ID           bigint        DEFAULT 0,
    A_J_ID           bigint        DEFAULT 1,
    G_E_ID           bigint        DEFAULT 0,
    G_J_ID           bigint        DEFAULT 1,
    G_RATTIGH        varchar(1000),
    G_FORBEH         varchar(3),
    ANVANDO          varchar(1000),
    ACCNR            varchar(15),
    TIDIG            varchar(10),
    SENAST           varchar(10),
    DOKTITEL         varchar(256),
    F_T_ID           bigint        DEFAULT 1,
    SAKORD           varchar(128),
    KOMMENT_FF       varchar(4000),
    REFKOD           varchar(15),
    TIDIGNR          varchar(30),
    INVENTNR         varchar(15),
    FILNAMN          varchar(256),
    FIL_LITEN        varchar(256),
    FIL_STOR         varchar(256),
    FIL_ORIGINAL     varchar(256),
    HOJD             varchar(20),
    BREDD            varchar(20),
    SVVITFARG        varchar(10),
    NEGPOS           varchar(10),
    GENPAS           varchar(10),
    BILDBAR          varchar(10),
    DIAM             varchar(20),
    MATERIAL         varchar(50),
    FUNKTION         varchar(500),
    TEKNIK           varchar(50),
    RAM              varchar(10),
    TILLSKAT         varchar(60),
    TILLSTAND        varchar(1000),
    OBSDATUM         varchar(10),
    OBSNAMN          varchar(50),
    ATGARD           varchar(1000),
    ATDDATUM         varchar(10),
    SIGN             varchar(30),
    FORPLATS         varchar(35),
    OVRIGT           varchar(30),
    OBJTYP           varchar(10),
    F_OPLATS         varchar(64),
    NODEID           bigint,
    `OPTIONS`        bigint        DEFAULT 0,
    DELETEDDATE      date,
    FULLTEXT INDEX ft_foto_doktitel_komment (DOKTITEL, KOMMENT_FF)
) ENGINE = InnoDB;
