CREATE TABLE SJOMAN
(
    POSTNR      bigint NOT NULL PRIMARY KEY,
    FORNAMN     varchar(50),
    EFTERNAMN1  varchar(40),
    EFTERNAMN2  varchar(40),
    IDNR        bigint,
    FODDAT      varchar(20),
    ALDER       varchar(20),
    FODFORS     varchar(80),
    FODPLATS    varchar(80),
    HEMFORS     varchar(80),
    HEMPLATS    varchar(80),
    CIVILSTAND  varchar(10),
    FAR         varchar(100),
    MOR         varchar(80),
    SJOMANSHUS  varchar(40),
    INSKRNR     varchar(14),
    INSKRDAT    varchar(20),
    BEFATTN     varchar(60),
    PAMONSTORT  varchar(60),
    PAMONSTDAT  varchar(20),
    AVMONSTORT  varchar(60),
    AVMONDAT    varchar(20),
    FARTYG      varchar(50),
    HEMMAHAMN   varchar(60),
    TYP         varchar(50),
    REDARE      varchar(80),
    KAPTEN      varchar(80),
    DESTINATION varchar(80),
    OVRIGT      varchar(2000),
    ANM         varchar(80),
    ARKIV       varchar(100),
    VOLYM       varchar(30),
    ARKISNR     varchar(22),
    SIDA        varchar(30),
    INDEX IDX_SJOMAN_ENAMN (EFTERNAMN1),
    INDEX IDX_SJOMAN_FNAMN (FORNAMN),
    INDEX IDX_SJOMAN_FODDAT (FODDAT)
) ENGINE = InnoDB;
